name: Bad Guy Better
favicon: null
layout_spectrum: 0.17193
typography_spectrum: 0.68142
title: Bad Guy Better
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090804'
    - '#f6c489'
    - '#737b6e'
    - '#fa4647'
  brandStrength: 0.7914663346018642
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
